<h1 align="center">EQE512 MATRIX METHODS IN STRUCTURAL ANALYSIS 
<br>
<br>
Week 05
<br>
<br>
Beam member w/ span load & Column member</h1> 

<h3 align="center">Dr. Ahmet Anıl Dindar (adindar@gtu.edu.tr)</h3> 
<h4 align="center">2021 Fall  </h4> 

---
**Today's Topics**

1- Beam system stiffness matrix

2- Beam member with span load

3- Column member stiffness matrix

In [ ]:
import numpy as np

## Beam System Stiffness Matrix

In [22]:
########### PLEASE FILL THE MATRIX GIVEN BELOW IN YOUR MIDTERM EXAM ###########
def beam_stiffness_matrix( member_props ):
    """
    member_props
    
    Example: 
    member_1 = {"E":30_000 ,  "I" : 26E-4 * 1.E12 ,  
                "jointI": joint_nodes[1] , 
                "jointJ": joint_nodes[2]}
                
    Returns    
    k: Member Stiffness matrix
    """
    
    import numpy as np
    E = member_props["E"]
    I = member_props["I"]
    
    # Length of the member
    delta_1 = member_props["jointJ"][0] - member_props["jointI"][0] 
    delta_2 = member_props["jointJ"][1] - member_props["jointI"][1] 
    L = (delta_1**2 + delta_2**2)**.5
    
    # Let's denote some terms
    twelveEIL3 = 12*E*I/(L**3)
    sixEIL2 = 6 * E * I / (L**2)
    fourEIL = 4 * E * I / (L)
    twoEIL =  2* E * I / (L)
    
    # Finally, the member stiffness matrix
    K = np.array( [[ twelveEIL3 , sixEIL2 , -1* twelveEIL3 , sixEIL2],
                  [sixEIL2 , fourEIL , -1* sixEIL2 , twoEIL],
                  [-1* twelveEIL3 , -1 * sixEIL2 , twelveEIL3, -1*sixEIL2],
                  [sixEIL2 , twoEIL , -1*sixEIL2 , fourEIL]])
                  
    return( K )


### Let's demonstrate

<img src="figures/beam_example_01.png" width="80%">

In [31]:
DOF = 2

joint_nodes = {1:[0,0] , 2:[0,1_000], 3:[0, 2_000]}

member_nodes= {1:[1,2] , 2:[2,3]}

member_1 = {"E":30_000 ,  "I" : round((250*500**3)/12 ,0) ,  
                "jointI": joint_nodes[1] , 
                "jointJ": joint_nodes[2]}

member_2 = {"E": 30_000 , "I" : round((250*500**3)/12,0) , 
                "jointI": joint_nodes[2] , 
                "jointJ": joint_nodes[3]}

member_props = {}

for member_no , member_property in zip( member_nodes.keys() , [member_1 ,  member_2] ):
    
    member_props[ member_no ] = member_property   
    
member_props

{1: {'E': 30000, 'I': 2604166667.0, 'jointI': [0, 0], 'jointJ': [0, 1000]},
 2: {'E': 30000, 'I': 2604166667.0, 'jointI': [0, 1000], 'jointJ': [0, 2000]}}

In [32]:
k_members = {}

for member_no , member_property in member_props.items() : 
    print( member_no)
    k_members[member_no] =  beam_stiffness_matrix(member_property  )
    
    print( "="*100 , "\n" , k_members[member_no])
    
print( "~"*100)    


1
 [[ 9.3750e+05  4.6875e+08 -9.3750e+05  4.6875e+08]
 [ 4.6875e+08  3.1250e+11 -4.6875e+08  1.5625e+11]
 [-9.3750e+05 -4.6875e+08  9.3750e+05 -4.6875e+08]
 [ 4.6875e+08  1.5625e+11 -4.6875e+08  3.1250e+11]]
2
 [[ 9.3750e+05  4.6875e+08 -9.3750e+05  4.6875e+08]
 [ 4.6875e+08  3.1250e+11 -4.6875e+08  1.5625e+11]
 [-9.3750e+05 -4.6875e+08  9.3750e+05 -4.6875e+08]
 [ 4.6875e+08  1.5625e+11 -4.6875e+08  3.1250e+11]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


**Let's compile the system stiffness matrix**

In [36]:
K = np.zeros( (len(joint_nodes) * DOF , len(joint_nodes) * DOF) , dtype=int)

print("K=", K,"\n"+"="*100)

for beam_no , beam_node in member_nodes.items() :     
    
    k_temp = k_members[ beam_no]
    
    print( "~"*100 , f"\n{beam_no} member","\n" , k_temp ,"\n"+"="*100)
    
    for counter_i , i in enumerate( beam_node ): 
        
        for counter_j , j in enumerate(beam_node) :
            
            print( i, j,"\n"+"="*100)
            
            add_k = k_temp[ counter_i * DOF  : counter_i * DOF + DOF  , counter_j * DOF  : counter_j * DOF + DOF  ] 
            
            print(  add_k , "\n"+"="*100)
            
            if i == 1 and j == 1 : 
                print(K[ 0  : DOF  , 0  : DOF] ,"=\n", K[ 0  : DOF  , 0  : DOF ] ,"+\n", add_k ,"\n"+"_"*100)
                
                K[ 0  : DOF  , 0  : DOF] = K[ 0  : DOF  , 0  : DOF ] + add_k
                
            else:
                
                print( K[ i * DOF - DOF  : i * DOF   , j * DOF - DOF : j * DOF  ] ,"=\n" ,K[ i * DOF - DOF  : i * DOF  , j * DOF - DOF : j * DOF  ]  ,"+\n" , add_k,"\n"+"_"*100)
                
                K[ i * DOF - DOF  : i * DOF   , j * DOF - DOF : j * DOF  ] = K[ i * DOF - DOF  : i * DOF  , j * DOF - DOF : j * DOF  ] + add_k                             
            print( K ,"\n"+"~"*100 )    

K= [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
1 member 
 [[ 9.3750e+05  4.6875e+08 -9.3750e+05  4.6875e+08]
 [ 4.6875e+08  3.1250e+11 -4.6875e+08  1.5625e+11]
 [-9.3750e+05 -4.6875e+08  9.3750e+05 -4.6875e+08]
 [ 4.6875e+08  1.5625e+11 -4.6875e+08  3.1250e+11]] 
1 1 
[[9.3750e+05 4.6875e+08]
 [4.6875e+08 3.1250e+11]] 
[[0 0]
 [0 0]] =
 [[0 0]
 [0 0]] +
 [[9.3750e+05 4.6875e+08]
 [4.6875e+08 3.1250e+11]] 
____________________________________________________________________________________________________
[[     937500   468750000           0           0           0           0]
 [  468750000 -2147483648           0           0           0           0]
 [          0           0           0           0           0           0]
 [          0           0           0           0           0           0]
 [          0           0           0   

---
# Beam member with span load 

<img src="figures/11-EQE512-Loads.PNG"   style="width:60%">

---
## Unloaded

_Similar to the Truss elements, the loads act on the nodes._


---
## Loaded

**Uniform Loading**

<img src="./figures/10a-EQE512-BeamLoading-Uniform.png" width="60%">

**Triangle Loading**

<img src="./figures/10b-EQE512-BeamLoading-Triangle.png" width="60%">

**Point Loading**

<img src="./figures/10c-EQE512-BeamLoading-SingleLoad.png" width="60%">

**Trapezoidal Loading**

<img src="./figures/10d-EQE512-BeamLoading-Trapz.png" width="60%">

**Solution :**

1. Obtain the equivalent end forces
2. Apply the obtained values in opposite directions at the nodes
3. Ignore the span loads

<img src="./figures/12-EQE512-Loads-Apply.PNG"   style="width:70%">


## Columns

**Freedom**

<img src="figures/9-EQE512-ColumnMemberExplanation.PNG" width="100%">

---

**Transformation Matrix**

Remember the relation between local and global terms

$$ k^i = (T^i) \hat{k}^i T^i$$

Remember the transformation matrix;

$$ T^i = \begin{bmatrix} \frac{\Delta_1}{L} & \frac{\Delta_2}{L}  & 0 & 0  \\ 0 & 0 & 
\frac{\Delta_1}{L} & \frac{\Delta_2}{L}  \end{bmatrix}$$

---

**Local Stiffness Matrix**

<img src="figures/column_stiffness_in_local_coordinates.png" width="60%">

**Global Stiffness Matrix**

After applying the transformation matrix

<img src="figures/9-EQE512-ColumnMemberStiffness.PNG" width="100%">

---

**NEXT WEEK**
The topics for the next week 

- "Frame Systems- Moment Resisting Frames with truss/tension members with truss/tension members"


<img src="http://worshiphousemedia.s3.amazonaws.com/images/main/s/st/bnt/st/seeyounextweek1.jpg" width="30%" >



